### ISSUE TITLE
Today's forecast and high/low temperatures

### ISSUE THREAD

**Issue by jat255** [k-donn/plasmoid-wunderground#16]
Thanks for such a great plasmoid @k-donn! 

I was thinking, I often look at this plasmoid in the morning to get a sense of what to expect for the day, and there's two places that could be improved. 

On the "Forecast" tab, including the current day's forecast would be great (it currently starts on the next day, but it looks like today's data is included in the API response).

Also, on the "Details" tab, including today's forecasted high and low temperatures could be a nice addition as well. It looks like the current data API does not include this, so it would have to be sourced from the forecast API. 

I'd be interested in helping add this, but I have never done any plasmoid development, so I'm not exactly sure where to start.

**Comment by jat255** [comment]
Point 1 above looks like maybe just changing this loop from starting at 1 to 0 might do it?

https://github.com/k-donn/plasmoid-wunderground/blob/733d26aba42632b1cb638502da82d8b2c45b4fc0/plasmoid/contents/code/pws-api.js#L145

**Comment by k-donn** [comment]
Hey, thanks for using my widget and making suggestions!

For the first point, after 3:00pm or 15:00 local time the API stops sending daytime forecast information. After 15:00, the API only sends the nighttime forecast. That was why the loop you mentioned starts at `1` and not `0` since the `0`th element might not have all the info on it. I was lazy earlier and didn't think about implementing something to get around this.

However, it sends the current day forecast prior to 15:00 and I could add that. I would just have to add in a check to make sure that the `day` object at [pws-api.js:148](https://github.com/k-donn/plasmoid-wunderground/blob/733d26aba42632b1cb638502da82d8b2c45b4fc0/plasmoid/contents/code/pws-api.js#L148) is not null. If `day` is null, then I would write the current-night forecast values to the `forecastModel`.

For point 2, I would add the high/low information at the top of the widget itself next to the icon and condition statement. 
![new-design](https://user-images.githubusercontent.com/58149779/118876520-55a1e300-b8bb-11eb-871e-45644214d4fa.png)
Something like that; I think it would flow better.

If you want to get more into plasmoid development, check out [Zren's](https://github.com/zren) [tutorial](https://zren.github.io/kde/docs/widget/#default-widgets) on development. He's helped me a bunch, and thanks again for the input!

**Comment by k-donn** [comment]
I don't really know what controls the plasmoid style on KDE plasma. As far as I know, the linux distribution you are on changes it. 
I've been wanting to give this widget the attention it needs, and I'll be happy to care of these changes!

**Comment by jat255** [comment]
Hooray! Thanks!

![image](https://user-images.githubusercontent.com/1278301/119721633-94d6b380-be28-11eb-942e-82085865aef1.png)
