### ISSUE TITLE
High / Low not displaying - for Imperial

### ISSUE THREAD

**Issue by rancod99** [k-donn/plasmoid-wunderground#20]
High / Low not displaying - for Imperial units ( gets stuck on Loading..). Works just fine with Celsius.

Thank you,

**Comment by k-donn** [comment]
Ok, thanks for bringing up the issue. 

To clarify, does the entire widget show the `Loading ...` screen or does just the top of the widget with the `High/Low` data show `Loading`; also, does the forecast page show up when the error occurs?

Screen shots would be helpful! Thanks!

**Comment by rancod99** [comment]
![image](https://user-images.githubusercontent.com/30396669/124309386-a3f00600-db38-11eb-9527-fba6596b4151.png)

**Comment by rancod99** [comment]
![image](https://user-images.githubusercontent.com/30396669/124309507-ce41c380-db38-11eb-8b3b-be3bedf3c3ac.png)

**Comment by k-donn** [comment]
Thanks!

Going through the logic in: https://github.com/k-donn/plasmoid-wunderground/blob/b25cbb31ab41a07524b86b3ad91b1023e26f12fa/plasmoid/contents/code/pws-api.js#L112
If there were an error with the request, then an error message should show up on the entire widget. 
There is no central error message, therefore, there is not an error with the request.
Because the `High/Low` part of the widget shows `loading...`, the variable `showForecast` must be false.
Therefore, there is some processing error between lines 142-200.

Because this only occurs for imperial units, I think the JSON from Wunderground might be different for some reason.

Sorry, but I have some more questions.

Does this happen for all stations you choose or just a certain one?

Also, could you please show me your plasmashell log?
Make sure `Write to console.log` is checked under the `Debug` settings in the widget. 
Then `journalctl /usr/bin/plasmashell -f` and change the units to imperial. 

Thanks again for bringing up this issue.

**Comment by k-donn** [comment]
[This](https://pastebin.com/HFzEgV5m) is a normal log for choosing a station,
