### ISSUE TITLE
window text is not uniform/cut out

### ISSUE THREAD

**Issue by capoei** [k-donn/plasmoid-wunderground#21]
![Screenshot_20210630_221222](https://user-images.githubusercontent.com/22452408/124050326-bbbc7280-d9f0-11eb-8561-0dcc887747f7.png)

also why can't I choose SBSV as weatherstation ID? it is our airport but closer to my home

**Comment by k-donn** [comment]
First off, love your desktop!

When you say text is `cut out`, I assume you mean text on the widget isn't visible because the widget is sized too small. In that case, I think you would want an option to configure the font size of the widget or what properties are visible on the widget so everything would fit. That is my plan for the next major version of the widget to add those features. 

I also think that `not uniform` means the same thing.

Sorry that you can't choose [SBSV](https://www.wunderground.com/weather/SBSV) as a data source. I currently only support Wunderground personal weather stations as a source. Other Wunderground sources are not supported. A current [side project](https://github.com/k-donn/plasma-ion-wundergroundpws) is an [Ion](https://techbase.kde.org/Projects/Plasma/Weather/Ions) for KDE Plasma with Wunderground PWS stations. My plan is to integrate that project into this project. I would also like to make an Ion for other non-PWS Wunderground sources.

Thanks for opening! Feel free to comment what I did/did not get right!

**Comment by capoei** [comment]
yes, the proposed changes for v3 will probably fix my issues, thanks.
I only know understood what Wunderground realy is. cool that there is a person in my city contributing to this comunity.
well.
thanks for the code. have a nice day
