### ISSUE TITLE
Plasma 6 widget not displaying weather icons/graphics

### ISSUE THREAD

**Issue by edwardp3** [k-donn/plasmoid-wunderground#52]
**Describe the bug**

Installed Plasma 6 widget (version 2.5.5) on openSUSE Tumbleweed, no weather icons or graphics (sun, clouds) are displayed.

**To Reproduce**

Install Plasma 6 widget on KDE Plasma 6, configure as normal. Weather icons/graphics not displayed/
**Screenshots**

![Screenshot_20240313_205042](https://github.com/k-donn/plasmoid-wunderground/assets/73129450/167154a8-1f30-4493-864f-1ce6d5060aa6)

![Screenshot_20240313_205058](https://github.com/k-donn/plasmoid-wunderground/assets/73129450/18a5ef8e-ca1d-46b9-bc9f-820905260b76)

**Desktop (output of `plasmashell --version && kf5-config --version`):**

plasmashell 6.0.1
KDE Frameworks: 6.0.0
Qt version: 6.6.2
```
plasmashell --version && kf6-config --version
plasmashell 6.0.1
 kf6-config: command not found
```

**Additional context**

**Comment by demmm** [comment]
This is caused by hardcoding of an images/icon path, non-exiting on normal installs:
https://github.com/k-donn/plasmoid-wunderground/blob/plasma6-release/plasmoid/contents/ui/CompactRepresentation.qml#L25
https://github.com/k-donn/plasmoid-wunderground/blob/plasma6-release/plasmoid/contents/ui/ForecastItem.qml#L62

To make it work right now, hardcode it to your local settings, until it is fixed here.
After adjusting those lines here:
![Screenshot_20240315_124926](https://github.com/k-donn/plasmoid-wunderground/assets/5360485/4abfbcf3-addc-458a-9db6-3383e1bdf929)

**Comment by edwardp3** [comment]
It looks like the entry for Line 25 in the link above, has some omissions/typos in it, the path is not the same as shown in the line 62 link, so I used the same path shown in the line 62 link for both. 

However, there is no such /neon directory inside /home.

Otherwise, still no icons.

![Screenshot_20240315_090343](https://github.com/k-donn/plasmoid-wunderground/assets/73129450/746ad439-3022-48c7-aab9-7e854962a62d)

![Screenshot_20240315_090357](https://github.com/k-donn/plasmoid-wunderground/assets/73129450/439e06dc-3e48-4485-8e85-491ada6109e4)

**Comment by k-donn** [comment]
Thanks for your interest in the widget!

This is a known problem in the plasma6 port. See #49.

I was testing to see if absolute paths worked on my system, and that is the only option that works so far. 
I think I will change the icons to `Kirigami` raster icons instead of themed SVGs for now.

Loading themed SVGs never worked with relative paths and `libplasma5` had a `plasmoid.file` method that searched the user system for the file and returned an absolute path. `libplasma6` does not have this method so the loading has not worked.

**Comment by edwardp3** [comment]
I removed the directory for it, then reinstalled the widget anew, thus restoring the file that was changed to what it was  showing originally (line 25). I will wait for the fix.

**Comment by k-donn** [comment]
I just pushed 0.0.4 on the KDE Store and changed the icons. My system has been known not to be representative for testing, so it would be great if you could check it out and see how it's doing!

**Comment by edwardp3** [comment]
Thank you for the update. Just installed the new widget.

It looks good.

![Screenshot_20240317_002259](https://github.com/k-donn/plasmoid-wunderground/assets/73129450/38331c31-1aa6-42fc-af51-e294c4780de1)

![Screenshot_20240317_002317](https://github.com/k-donn/plasmoid-wunderground/assets/73129450/3a72d916-85b7-4397-b9d8-22a496882d74)

**Comment by edwardp3** [comment]
I was wondering about the folded sheet of paper icon for the wind direction, whether it should be something else, then I thought about it. 

In a way, it makes sense. A piece of paper is light, blowing around in the wind.

**Comment by k-donn** [comment]
Hahahaha, thank you. The paper is a stop-gap measure until the widget can load custom wind vane icons properly. But I am glad it makes sense until then.

**Comment by k-donn** [comment]
Got it. Line 30 of [`psw-api.js`](https://github.com/k-donn/plasmoid-wunderground/blob/plasma6-release/plasmoid/contents/code/pws-api.js#L30) should be `weather-freezing-rain-symbolic`.

**Comment by tabascosw** [comment]
Are you sure, I think it still should be 'weather-few-clouds-symbolic', it looked a bit funny this morning here. Almost no clouds. I checked the wunderground page for my location and it gave me 'weather-few-clouds-symbolic' = 30.

**Comment by k-donn** [comment]
I see where the confusion is. 
@tabascosw line 30 of the file `pws-api.js` needed to be changed, but not the value of key 30 in the JSON object. You are correct. The value of key 30 is the right icon name. 

Line 30 corresponds to key 7 of the JSON object, which has the incorrect name. @edwardp3  A new version that fixed the wintry mix icon and the paper icon is out.

**Comment by edwardp3** [comment]
The Plasma 6 applet cannot be updated in the same manner as the Plasma 5 applet. Discover doesn't see it, it must first be deleted from the Plasmoid directory, then deleted from the directory of applets, then a system reboot to make sure the old applet is gone. Then reinstalled. In my opinion, KDE 6 was released prematurely.

The new applet was installed. If the wind direction arrow is designed to point in the wind direction shown, it's incorrect.

![Screenshot_20240320_205909](https://github.com/k-donn/plasmoid-wunderground/assets/73129450/f9f9202d-297e-468b-b8fb-a887e85ebb6a)

![Screenshot_20240320_210604](https://github.com/k-donn/plasmoid-wunderground/assets/73129450/b5999817-6fab-4fc3-b5e8-8f7d920081e7)

**Comment by k-donn** [comment]
Thanks for checking it! Yeah, testing new versions of the plasmoid is quite slow and annoying. I previously used `kpackagetool5` to update the plasmoid, but `kpackagetool6` does not work. :(

What I feared was true for the arrow: it does not rotate around its tail but instead in the middle of the arrow. This will require a proper `Rotation` QML type to be applied instead of just setting a number to the `rotation` property. I will push this out.

Using the old icons that I put a lot of effort into is my priority, and I delegate most of my time to this. I am still asking/searching for a solution. In the future, I will leave an option to use system-themed icons instead of my custom bundled ones.

Until then, thank you again for using the widget!

**Comment by edwardp3** [comment]
I'm pleased to use it.

It's 10:19 PM / 22:19 here currently and the widget is now displaying the current conditions (from both stations) as sun and clouds. Curious as to what calls the icons. Although it rained earlier, the current icon probably should be moon and clouds.

![Screenshot_20240320_221920](https://github.com/k-donn/plasmoid-wunderground/assets/73129450/f53fed68-411e-4ad3-9a3e-0ca6679cf883)

**Comment by mozo78** [comment]
Hello, I also have a strange sheet insted of arrow. Can you tell me how to fix it?
![Screenshot_2024_24_07_0_14](https://github.com/user-attachments/assets/5dc76585-64c2-4558-bc9d-247c02d8348d)

**Comment by k-donn** [comment]
@mozo78 I think the problem comes from the icon name the widget uses: `gnumeric-object-arrow`. You should look in Cuttlefish and see if you have that icon in your theme.

I assumed it was a standard icon but I now see that it is not, sorry. Installing an icon named  `gnumeric-object-arrow` should solve the problem, or changing icon themes to one that has it would solve it. 

Sorry again because those would be pretty annoying solutions. The end goal solution is using the custom SVGs I made but plasma 6 is making that hard.

**Comment by mozo78** [comment]
It's not a such big problem, don't worry :)



> Installing an icon named `gnumeric-object-arrow` should solve the problem

How shoud I do that?

I saw the icon that the widget is getting :)
![Screenshot_2024_25_07_0_16](https://github.com/user-attachments/assets/f208d8fb-e48a-489b-969d-316371b9cd40)

**Comment by k-donn** [comment]
You place the file [gnumeric-object-arrow.svg](https://github.com/user-attachments/assets/02e472ba-29c2-4afa-b4b2-a633d476ffa2) into your theme's icon directory. Make sure it gets saved to disk with that name.

The exact directory depends on the theme you are using. I am using breeze-dark so it is at:
```
/usr/share/icons/breeze-dark/actions/22/gnumeric-object-arrow.svg
```
In short, put it in the `actions` directory part of your theme. The structure is different for some themes. For oxygen, the `actions` dir is at:
```
/usr/share/icons/oxygen/base/22x22/actions/
```
The directory for your theme may be at `~/.local/share/icons/` so search there too. With some poking around you should hopefully be able to find it!

**Comment by mozo78** [comment]
Yes it's working, thank you for your splendid work!!!
