### ISSUE TITLE
Plasma6 widget shows only temperature

### ISSUE THREAD

**Issue by GITMichaelK** [k-donn/plasmoid-wunderground#57]
Using the plasmaoid under
```
Operating System: Manjaro Linux 
KDE Plasma Version: 6.0.4
KDE Frameworks Version: 6.1.0
Qt Version: 6.7.0

```it looks like this
[Screenshot](https://github.com/k-donn/plasmoid-wunderground/assets/34304987/9604ea44-fce2-4dca-9af4-0cb8146cd141)

How to solve this? Thank you for your work!

**Comment by k-donn** [comment]
Interesting, the text is very dim. Is it like this when the widget background is transparent or opaque, or both?

**Comment by GITMichaelK** [comment]
Thank you, but I have no idea about 
`widget background is transparent or opaque, or both?`
![Screenshot_20240520_090324](https://github.com/k-donn/plasmoid-wunderground/assets/34304987/ae4cdf87-ae13-451f-a1b3-ac3712601dff)

There is not even a setting for that. I guess, it's transparent.

**Comment by k-donn** [comment]
The transparency setting is in the context menu of the widget when you enter edit mode. The settings page is also strangely dark. All of the page should be white instead of just the side bar and the spin boxes.
![Transparent](https://github.com/k-donn/plasmoid-wunderground/assets/58149779/b3f3a724-07db-411b-add8-49460fd05919)
![Opaque](https://github.com/k-donn/plasmoid-wunderground/assets/58149779/dce4f912-a229-4c7a-ac84-1a6453e0c4a8)

**Comment by GITMichaelK** [comment]
Thank you, found it. Now it works!
