### ISSUE TITLE
Pressure Indicator

### ISSUE THREAD

**Issue by tabascosw** [k-donn/plasmoid-wunderground#70]
Not sure if it is only my setup, but the pressure indicator always indicates rapid falling, no matter what the actual trend is. First I thought it would be an issue with the translation, but that is not the case. This happens on two separate installations, one in openSUSE Tumbleweed and one in openSUSE Slowroll. The information in text form is actually correct, even though the information from wunderground is always in english (instead of risen it should be 'gestiegen'. 
![Bildschirmfoto_20240805_082215](https://github.com/user-attachments/assets/f44b151c-ff90-4622-aa98-2833c96a8be4)

**Comment by k-donn** [comment]
I see the problem here. Wunderground API gives a translated, single word description.
One of: `Steady, Rising, Falling, Rapidly Rising, Rapidly Falling`.
https://github.com/k-donn/plasmoid-wunderground/blob/5458576a492fc7dfb429ef76f18f800d04d92bb5/plasmoid/contents/code/utils.js#L419
This function gives the icon to show based on the English single word description. When the API returns a non-English word, that function will always return the double down arrow. The API returns a `pressureTendencyCode` field which is a `0...4` field that I will change the function to use.

As for "risen" and "fallen" always being in English, they come from a different function.
https://github.com/k-donn/plasmoid-wunderground/blob/5458576a492fc7dfb429ef76f18f800d04d92bb5/plasmoid/contents/code/utils.js#L433
I think the most efficient way to fix that is to create two i18n entries. One entry for "Pressure has risen XX in the last three hours," and one for "Pressure has fallen XX in the last three hours." Then, the widget will choose which to display based on the pressure change. 

Thanks for bringing this up!

**Comment by tabascosw** [comment]
Looks like your changes work, the pressure has fallen a little bit and the indicator correctly shows that. I've attached the updated German locale to reflect the changes here as well. Thank You. This is getting better and better.
![Bildschirmfoto_20240806_164910](https://github.com/user-attachments/assets/30ec61bb-6983-4bb1-a773-6874c3d61af0)
[de_DE.tar.gz](https://github.com/user-attachments/files/16511987/de_DE.tar.gz)

**Comment by k-donn** [comment]
Awesome!
